server.port=8083
spring.application.name=order-service

# MongoDB Atlas Connection (අලුත් version එකට අනුව update කර ඇත)
spring.mongodb.uri=mongodb+srv://appuser:RM0IQtzcyxG9hx4W@cosmicapparelcluster.u03hcy4.mongodb.net/cosmic_orders_db?retryWrites=true&w=majority

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Config Server (පාවිච්චි නොකරන්නේ නම් මෙය ඉවත් කරන්න)
spring.config.import=optional:configserver:http://localhost:8888